server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-db
#      host: localhost
#      port: 27017
#      username: root
#      password: 12345
#      database: customer-db
#      authentication-database: admin
