server:
  port: 7020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:5432/order-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

web-client:
  config:
    customer-url: http://localhost:7000/api/customer
    product-url: http://localhost:7010/api/product
    payment-url: http://localhost:7030/api/payment