server:
  port: 7030

eureka:
  client:
    serviceUrl:
      defaultService: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PAYMENT-DB
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true