services:
  postgres:
    container_name: postgres_service
    image: postgres
    environment:
      POSTGRES_USER: fuji
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - microservices_net

  pgadmin:
    container_name: postgres_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices_net

  mongodb:
    container_name: mongodb_services
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    restart: always

  maildev:
    container_name: mail_dev_service
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices_net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: